version: '3'
services:
  mango1:
    image: server
    environment:
      - APP=mango
    ports:
      - "8081:5000"
  mango2:
    image: server
    environment:
      - APP=mango
    ports:
      - "8082:5000"
  yandex1:
    image: server
    environment:
      - APP=yandex
    ports:
      - "9081:5000"
  yandex2:
    image: server
    environment:
      - APP=yandex
    ports:
      - "9082:5000"
